import { useEffect, useState } from 'react'
import AppChrome from '../../components/AppChrome.jsx'
import ThemePicker from '../../components/ThemePicker.jsx'
import { dashboardApi } from '../../lib/api.js'

const appointments = [
  { time: '09:00', duration: '60 min', name: 'Mariana Torres', type: 'Primera consulta', initials: 'MT', color: 'coral', status: 'Confirmada' },
  { time: '10:30', duration: '45 min', name: 'Diego Ramírez', type: 'Seguimiento', initials: 'DR', color: 'blue', status: 'Confirmada' },
  { time: '12:00', duration: '60 min', name: 'Sofía Hernández', type: 'Seguimiento', initials: 'SH', color: 'purple', status: 'Por confirmar' },
  { time: '16:30', duration: '45 min', name: 'Jorge Castillo', type: 'Control rápido', initials: 'JC', color: 'yellow', status: 'Confirmada' },
]

export default function DashboardPage({ setActive }) { const [data,setData]=useState({stats:{appointments:4,pendingConfirmations:1,followUps:3,activePatients:5},appointments}); useEffect(()=>{dashboardApi.today('2026-08-26').then(response=>{if(response?.stats)setData(response)}).catch(()=>{})},[]); return <AppChrome active="Hoy" setActive={setActive}><ThemePicker /><div className="content"><section className="welcome"><div><p className="eyebrow">MIÉRCOLES, 26 DE AGOSTO</p><h1>Buenos días, Gabriela <span>✦</span></h1><p className="subtitle">Tu práctica, tus pacientes, un solo lugar.</p></div><button className="primary" onClick={()=>setActive('Agenda')}><span>+</span> Nueva cita</button></section><section className="stats-grid">{[['Citas de hoy',data.stats.appointments,'◷'],['Por confirmar',data.stats.pendingConfirmations,'◌'],['Seguimientos',data.stats.followUps,'◒'],['Pacientes activos',data.stats.activePatients,'♧']].map(([label,value,icon])=><div className="stat-card" key={label}><div className="stat-head"><span>{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value">{value}</div><div className="stat-foot"><span>Actualizado desde tu API</span></div></div>)}</section><div className="dashboard-grid"><section className="panel appointments"><div className="panel-title"><div><h2>Agenda de hoy</h2><p>Consultas persistentes</p></div><button className="link-button" onClick={()=>setActive('Agenda')}>Abrir agenda →</button></div><div className="day-line"><span className="today-pill">HOY</span><span>Miércoles 26 de agosto, 2026</span></div><div className="appointment-list">{data.appointments.map((item,index)=><div className="appointment" key={item.id||item.name}><div className="time"><b>{item.time||new Date(item.startAt).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</b><small>{item.duration||'60 min'}</small></div><div className={'person-avatar '+(item.color||['coral','blue','purple','yellow'][index%4])}>{item.initials||item.patient?.firstName?.[0]||'P'}</div><div className="appointment-info"><b>{item.name||`${item.patient?.firstName||''} ${item.patient?.lastName||''}`}</b><span>{item.type||'Consulta'}</span></div><span className={'status '+(item.status==='CONFIRMED'||item.status==='Confirmada'?'confirmed':'pending')}>{item.status==='CONFIRMED'?'Confirmada':item.status==='PENDING_CONFIRMATION'?'Por confirmar':item.status}</span></div>)}</div></section><section className="panel followups"><div className="panel-title"><div><h2>Próxima acción</h2><p>Un pendiente para hoy</p></div></div><div className="next-action-card"><span className="stat-icon orange">◌</span><div><b>Confirmar cita de Sofía</b><small>Hoy · 12:00 · Seguimiento</small></div><button className="message">Recordar ↗</button></div><div className="empty-note"><span>✓</span><p>El resto de tu agenda está en orden</p></div></section></div></div></AppChrome> }
