import { PrismaClient } from '@prisma/client'

// Loads the ~70 real recipes from the nutritionist's own working spreadsheet
// (DIETOCALCULO.xlsx, sheet "Recetas") into the Recipe/RecipeIngredient tables.
//
// Unlike the SMAE catalog (fase 14), this sheet has no structured columns — every recipe is a
// single free-text cell mixing name, ingredient list and preparation with inconsistent bullets,
// brand names and units. There is no reliable way to parse that programmatically without real
// risk of silently wrong nutrition data, so each recipe below was read and interpreted by hand:
// `ingredients` is the resulting best-effort structured list (ingredient name to search for in
// the catalog + quantity in grams), used only to calculate nutrition; `instructions` keeps the
// original text close to verbatim so the nutritionist can compare against the source. Quantities
// came from, in order of preference: (1) grams stated explicitly in the text, (2) the matched
// SMAE ingredient's own equivalence serving (e.g. "2 rebanadas" of a bread whose SMAE serving is
// "1 rebanada = 25 g" -> 50 g), (3) a standard conversion (1 cda ~15 g, 1 cdita ~5 g, 1 huevo
// ~44 g, 1 clara ~33 g). Pure seasoning/garnish "al gusto" items (sal, salsas, especias) were
// left out of the structured list on purpose — same convention SMAE itself uses for its
// "Libres en energía" group — and are still visible in `instructions`.
//
// Usage: node prisma/import-recetas.js [practiceId]
// Idempotent-ish: matches existing recipes by name and replaces their ingredients instead of
// creating duplicates on re-run.

const prisma = new PrismaClient()
const practiceId = process.argv[2] || '00000000-0000-0000-0000-000000000001'

// A handful of items from the recipes have no real match in the SMAE catalog (checked against
// the imported 2,915 items). Hand-authored here with realistic per-100g values, same convention
// as the rest of the hand-authored catalog (see prisma/seed.js).
const FALLBACK_INGREDIENTS = [
  { name: 'Yogur griego sin azúcar', group: 'Leche descremada', unit: 'gramos', nutrition: { kcal: 59, protein: 10, carbs: 3.6, fat: 0.4, calcium: 110 } },
  { name: 'Leche de coco baja en calorías', group: 'Grasas sin proteínas', unit: 'ml', nutrition: { kcal: 19, protein: 0.2, carbs: 3, fat: 0.5 } },
  { name: 'Chorizo vegano', group: 'Grasas con proteínas', unit: 'gramos', nutrition: { kcal: 180, protein: 16, carbs: 6, fat: 11 } },
]

// { query: string to search in Ingredient.name, grams: quantity for this recipe }
const RECIPES = [
  { name: 'Pizza de pollo búffalo', mealType: 'lunch', ingredients: [{ query: 'Pan pita', grams: 70 }, { query: 'Puré de jitomate', grams: 45 }, { query: 'Pechuga de pollo sin piel cocida', grams: 60 }, { query: 'Queso Mozzarella', grams: 45 }], instructions: '1 pan pita\n3 cdas de puré de tomate\n60g de pechuga desmenuzada con 1 cda de salsa búfalo\n45g de queso mozzarella\nCebolla y pimiento al gusto\n4 min en airfryer a 360F' },
  { name: 'Pizzeta de jamón', mealType: 'lunch', ingredients: [{ query: 'Pan pita', grams: 70 }, { query: 'Puré de jitomate', grams: 45 }, { query: 'Jamón de pavo', grams: 30 }, { query: 'Champiñón crudo rebanado', grams: 40 }, { query: 'Queso Mozzarella', grams: 45 }], instructions: '1 pan pita\n3 cdas de puré de tomate\n3 rebanadas de jamón de pavo\n3 a 4 champiñones\n45g de queso mozzarella\nCebolla y pimiento al gusto\n4 min en airfryer a 360F' },
  { name: 'Wrap de pollo', mealType: 'lunch', ingredients: [{ query: 'Pan árabe integral', grams: 60 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Pechuga de pollo sin piel cocida', grams: 60 }, { query: 'Queso Panela', grams: 30 }], instructions: '1 pieza de pan árabe integral con 1/3 de aguacate, 60g de pollo deshebrado y 30g de queso panela light con tiras de pimiento y cebolla. Acompañar encima con aguacate.' },
  { name: 'Sándwich (pan thin, jamón y queso panela)', mealType: 'snack', ingredients: [{ query: 'Pan thin', grams: 40 }, { query: 'Queso Panela', grams: 40 }, { query: 'Jamón de pavo', grams: 32 }, { query: 'Aguacate Hass', grams: 23 }, { query: 'Uva con semilla', grams: 45 }], instructions: '1 pieza de pan thin o flatout\n40g de queso panela fresco\n1.5 rebanadas de jamón de pechuga de pollo a las finas hierbas\nAlfalfa, pepino y tomate\n1/4 de aguacate hass\n9 uvas verdes\nInfusión de té verde' },
  { name: 'Sándwich Capprese', mealType: 'snack', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Queso Panela', grams: 40 }, { query: 'Jamón de pavo', grams: 21 }, { query: 'Jitomate', grams: 70 }, { query: 'Espinaca cruda', grams: 30 }, { query: 'Aceite de oliva', grams: 5 }], instructions: '2 rebanadas de pan cero cero\n40g de queso panela a la plancha\n1 rebanada de jamón\n1 tomate en rodajas\n1 taza de espinaca\n1 cdita de aceite de oliva\n1/3 de aguacate' },
  { name: 'Quesadillas con champiñones', mealType: 'lunch', ingredients: [{ query: 'Tortilla de maíz', grams: 60 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Champiñón crudo rebanado', grams: 60 }], instructions: '2 tortillas de maíz o 6 tortillas mission\n30g de queso Oaxaca\n1/2 taza de champiñones' },
  { name: 'Gringas con pollo', mealType: 'lunch', ingredients: [{ query: 'Tortilla de harina', grams: 75 }, { query: 'Queso Oaxaca', grams: 45 }, { query: 'Pechuga de pollo sin piel cocida', grams: 60 }, { query: 'Aguacate Hass', grams: 47 }], instructions: '3 tortillas mission\n45g de queso oaxaca\n1/4 taza de pechuga desmenuzada (60g)\n1/2 aguacate (puedes hacerlo guacamole)\nSalsa al gusto' },
  { name: 'Molletes', mealType: 'lunch', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Queso Oaxaca', grams: 45 }, { query: 'Frijoles refritos', grams: 80 }], instructions: '2 rebanadas de pan integral\n45g de queso oaxaca\n80g de frijol molido\nPico de gallo y salsa al gusto\n4 min en airfryer a 360F' },
  { name: 'Hot Cakes Red Velvet', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 27 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Betabel crudo', grams: 40 }], instructions: '1/3 de avena en hojuelas molida\n1 huevo entero o 1/4 de taza de claras de huevo\n1/4 de betabel\n1 cdita de vainilla\n1 pizca de canela\nStevia al gusto' },
  { name: 'Hot Cakes de plátano', mealType: 'breakfast', ingredients: [{ query: 'Clara de huevo', grams: 132 }, { query: 'Avena en hojuelas', grams: 40 }, { query: 'Plátano', grams: 100 }], instructions: 'Hot cakes saludables: 4 claras de huevo + 1/2 taza de harina de avena (licuar avena hasta obtener consistencia de harina) + 1 pizca de royal + 1/4 taza leche vegetal sin azúcar. Licuar y agregar agua o leche vegetal para dar la consistencia deseada. Agregar 2 cditas de cacao o canela al gusto. Cocinar en el sartén.\nToppings: 1 ración de fruta + jarabe de maple sugar free' },
  { name: 'Sandwich de pan pita', mealType: 'snack', ingredients: [{ query: 'Pan pita', grams: 70 }, { query: 'Jamón de pavo', grams: 21 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Jitomate', grams: 100 }], instructions: '1 pan pita taquero\n1 rebanada de jamón\n30g de queso oaxaca\n1/3 de aguacate\n1 cdita de aceite\n1 1/2 tomate\n1/4 cebolla\nAjo' },
  { name: 'Avocado Toast', mealType: 'breakfast', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Huevo entero fresco', grams: 100 }], instructions: '2 rebanadas de pan integral tostado + 2 cdas de guacamole o 1/3 de aguacate + 2 huevos duros o estrellados + verduras al gusto (espinacas, tomate, alfalfa, rábano)' },
  { name: 'French Toast y huevo', mealType: 'breakfast', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Plátano', grams: 100 }], instructions: '2 rebanadas de pan integral remojadas en 2 claras de huevo + 1/4 taza de leche vegetal sin azúcar, vainilla, canela y stevia + 1 ración de fruta + maple sugar free\nHuevo: 3 claras de huevo + verduras al gusto (espinacas, champiñones, tomate)' },
  { name: 'Huevo con jamón y champiñones', mealType: 'breakfast', ingredients: [{ query: 'Huevo entero fresco', grams: 88 }, { query: 'Jamón de pavo', grams: 42 }, { query: 'Champiñón crudo rebanado', grams: 60 }], instructions: '2 huevos o 1/2 taza de claras de huevo\n2 rebanadas de jamón\n1/2 taza de champiñones' },
  { name: 'Omelette Verde', mealType: 'breakfast', ingredients: [{ query: 'Espinaca cruda', grams: 30 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Jamón de pavo', grams: 42 }, { query: 'Champiñón crudo rebanado', grams: 30 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '1 taza de espinaca\n1 huevo entero y 2 claras\n30g de queso oaxaca light\n2 rebanadas de jamón de pavo\n1/4 taza de champiñones\n1/3 de aguacate hass\nLicuar la espinaca con huevo y claras, sal y pimienta; cocinar en el sartén con 1 cdita de aceite. Rellenar con queso, jamón y champiñones.' },
  { name: 'Frittata con mix de vegetales', mealType: 'breakfast', ingredients: [{ query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Jitomate', grams: 30 }, { query: 'Champiñón crudo rebanado', grams: 30 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Queso Oaxaca', grams: 30 }], instructions: 'Tortilla de huevo con tomate y champiñones.\n1 huevo entero y 2 claras\n1/4 tomate picado, 1/4 taza de champiñones\n1/3 de aguacate hass\n30g de queso oaxaca light\nBatir el huevo entero y las claras, agregar las verduras, sal y pimienta. Cocinar en el sartén con 1 cdita de aceite y dar vuelta.' },
  { name: 'Mega pancake de chocolate', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 26 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Harina de coco', grams: 15 }, { query: 'Fresas', grams: 150 }], instructions: '26g de harina de avena\n1 huevo y 1/4 taza de claras\n15g de harina de coco o almendra\n1 cda de cacao en polvo\n1 pizca de polvo para hornear y 1/2 splenda\nToppings: 150g de fresas o 1/2 plátano + 1 cda de spread de avellana' },
  { name: 'Croissant con jamón y queso', mealType: 'snack', ingredients: [{ query: 'Cuernito', grams: 60 }, { query: 'Queso Panela', grams: 60 }, { query: 'Aguacate Hass', grams: 15 }, { query: 'Jitomate', grams: 20 }], instructions: '1 cuernito integral con 1 rebanada de aguacate, mostaza, 60g de queso panela light o 4 cucharadas de pollo deshebrado, 1 rebanada de tomate sin semillas y germinado.' },
  { name: 'Burritas de jamón y queso', mealType: 'lunch', ingredients: [{ query: 'Tortilla de maíz', grams: 90 }, { query: 'Jamón de pavo', grams: 42 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '3 tortillas Mission de maíz ligeras\n2 rebanadas de jamón de pavo\n30g de queso Oaxaca light\n1/3 de aguacate hass' },
  { name: 'Chilaquiles fit con huevo', mealType: 'breakfast', ingredients: [{ query: 'Totopos de maíz', grams: 36 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Queso Cottage', grams: 30 }, { query: 'Yogur griego sin azúcar', grams: 15 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '1/2 taza de salsa verde\n36g de totopos susalia\n1 huevo estrellado\n2 cdas de queso cottage, 1 cda de yogurt griego sin azúcar (sustituto de crema)\n1/4 de aguacate, cebolla y cilantro al gusto' },
  { name: 'Omelette de queso, espinacas y champiñones', mealType: 'breakfast', ingredients: [{ query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 33 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Espinaca cruda', grams: 20 }, { query: 'Champiñón crudo rebanado', grams: 45 }, { query: 'Pan integral', grams: 25 }, { query: 'Naranja', grams: 130 }], instructions: '1 huevo y 1/4 taza de claras revueltas y salpimentadas\nRelleno: 30g de queso oaxaca, un puño de espinacas y 3 cdas de champiñones. Acompañar con 1 rebanada de pan integral y 1 naranja/pitahaya' },
  { name: 'Sandwich de quesos', mealType: 'lunch', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Jamón de pavo', grams: 63 }, { query: 'Queso de cabra', grams: 15 }, { query: 'Jitomate', grams: 45 }, { query: 'Espinaca cruda', grams: 15 }, { query: 'Queso Mozzarella', grams: 30 }], instructions: '2 rebanadas de pan integral\n3 rebanadas de jamón de pavo\n1 cda al ras de queso de cabra\n1/2 jitomate y espinaca al gusto\n30g de mozzarella/oaxaca' },
  { name: 'Blueberry Pancakes', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 40 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Yogur griego sin azúcar', grams: 50 }, { query: 'Arándano', grams: 35 }], instructions: '40g de harina de avena, 1 cdita de esencia de vainilla, 1/2 splenda, 1 huevo y 50g de yogurt griego sin azúcar\n1/4 taza de blueberries (mientras formas los pancakes)\nTopping: 2 cdas de spread de avellana' },
  { name: 'Pan tostado con jocoque y aguacate', mealType: 'breakfast', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Jocoque seco', grams: 15 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '2 piezas de pan tostado integral con 1 cucharada de jocoque seco reducido en grasa o requesón\n1 rebanada de aguacate\nAñadir germinado encima' },
  { name: 'Huevo motuleño', mealType: 'breakfast', ingredients: [{ query: 'Tostada de nopal horneada', grams: 10 }, { query: 'Frijoles refritos', grams: 30 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Jamón de pavo', grams: 21 }, { query: 'Chícharo', grams: 25 }], instructions: '1 tostada de nopal con 1 cucharada de frijol, 1 huevo estrellado con salsa de tomate natural revuelto con 2 cucharadas de chícharos y 1 rebanada de pechuga de pavo.\nAcompañar con 1 taza de lechuga orejona picada.' },
  { name: 'Hot Dog', mealType: 'lunch', ingredients: [{ query: 'Pan para hamburguesa chico', grams: 45 }, { query: 'Salchicha', grams: 45 }], instructions: '1 pieza de pan para hot dog con 1 salchicha asada u horneada en el microondas.\nAcompañar con x\'nipek y 1 taza de ensalada de lechuga, tomate y pepino.' },
  { name: 'Tacos de bisteck', mealType: 'lunch', ingredients: [{ query: 'Tortilla de maíz', grams: 60 }, { query: 'Bistec de res', grams: 60 }], instructions: '2 tortillas Torti Regias\n2 cucharadas de bisteck en cada taco\nRomanita o germinado\nSalsa roja o verde' },
  { name: 'Tostadas de queso panela o pollo', mealType: 'lunch', ingredients: [{ query: 'Tostada', grams: 20 }, { query: 'Queso Panela', grams: 80 }], instructions: '1 paquetito de tostadas Salmas con 80g de queso panela o 1 cucharada de pollo en cada tostada.\nAcompañar con 1 taza de ensalada de tomate y lechuga.' },
  { name: 'Smoothie', mealType: 'snack', ingredients: [{ query: 'Bebida vegetal Silk Almendra sin azúcar', grams: 240 }, { query: 'Fresas congeladas sin azúcar', grams: 80 }, { query: 'Avena en hojuelas', grams: 20 }, { query: 'Crema de cacahuate', grams: 15 }], instructions: '1 taza de leche vegetal sin azúcar + 1 ración de fruta congelada + 1/4 taza avena + 1/4 taza amaranto o granola + 1 cda de crema de almendras o cacahuate natural.\nOpcional: cacao, canela, stevia' },
  { name: 'Sándwich de huevo', mealType: 'breakfast', ingredients: [{ query: 'Pan integral', grams: 50 }, { query: 'Huevo entero cocido', grams: 88 }, { query: 'Hummus', grams: 30 }, { query: 'Naranja', grams: 130 }], instructions: '2 rebanadas de pan integral + 2 huevos duros o 4 claras con verduras + 2 cdas de hummus o guacamole + verduras al gusto (espinacas, tomate, germinado) + 1 ración de fruta.' },
  { name: 'Huevos al gusto', mealType: 'breakfast', ingredients: [{ query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 132 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Tostada', grams: 20 }], instructions: '1 huevo y 4 claras + verduras al gusto (tomate, cebolla, espinaca, chile dulce y chile serrano) + 1/3 aguacate + 1 paquete de tostadas Salmas' },
  { name: 'Tacos de carnitas de atún', mealType: 'lunch', ingredients: [{ query: 'Tortilla de nopal', grams: 69 }, { query: 'Atún en agua', grams: 90 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '3 tortillas de nopal + 90g de lomo de atún o 2 sobres de atún en agua bajo en sodio + verduras (cebolla, chile dulce, cilantro) + 1/3 aguacate o 2 cdas de guacamole + salsa verde. Picar el atún y las verduras en cubos y cocinar hasta la cocción deseada.' },
  { name: 'Tacos de fajitas low carb', mealType: 'lunch', ingredients: [{ query: 'Tortilla de nopal', grams: 69 }, { query: 'Pechuga de pollo sin piel a la plancha', grams: 90 }, { query: 'Hummus', grams: 30 }], instructions: '3 tortillas de nopal + 90g de pechuga de pollo o bistec de res o arrachera en fajitas (con pimientos, nopales o rajas poblanas) + salsa roja o verde + 2 cdas de hummus' },
  { name: 'Ensalada de nopales', mealType: 'lunch', ingredients: [{ query: 'Nopal cocido', grams: 100 }, { query: 'Jitomate', grams: 50 }, { query: 'Aceite de oliva', grams: 10 }, { query: 'Frijoles enteros', grams: 60 }], instructions: 'Verduras (nopal hervido, cebolla y tomate crudos, cilantro, chile serrano, 2 cdas vinagre y 2 aceite de oliva, sal y pimienta) + 4 cdas de frijol + 1 paquete de tostadas Salmas. Opcional: agregar 2 cdas de queso feta' },
  { name: 'Pizza de coliflor', mealType: 'lunch', ingredients: [{ query: 'Coliflor cocida', grams: 150 }, { query: 'Espinaca cruda', grams: 20 }, { query: 'Champiñón crudo rebanado', grams: 30 }, { query: 'Jamón de pavo', grams: 42 }], instructions: 'Base de coliflor (Costco), dividir en 8 pedazos y usar 3.\nAgregar encima espinaca, champiñones y 2 rebanadas de jamón picado, hornear.\nGuarnición: lechuga, germinado y pepino + 1 cdita de vinagre balsámico.' },
  { name: 'Lasagna de queso panela', mealType: 'lunch', ingredients: [{ query: 'Queso Panela', grams: 60 }, { query: 'Carne molida de pollo', grams: 120 }, { query: 'Espinaca cruda', grams: 30 }], instructions: 'Apilar 2 rebanadas de queso panela con 120g de carne molida de pollo o falda de res asada con espinaca + 3 cdas de salsa roja 4 quesos. Hornear.\nAcompañar con espárragos asados o brócoli.' },
  { name: 'Tostadas con frijol y pollo', mealType: 'lunch', ingredients: [{ query: 'Tostada', grams: 30 }, { query: 'Frijoles refritos', grams: 45 }, { query: 'Pechuga de pollo sin piel cocida', grams: 60 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '3 tostadas horneadas con 1 cda de frijol c/u\n2 cdas de pollo deshebrado c/u\nLechuga o tomate\n1/4 de aguacate\nSalsa verde o roja' },
  { name: 'Huevo con espinaca', mealType: 'breakfast', ingredients: [{ query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 132 }, { query: 'Espinaca cruda', grams: 40 }], instructions: '1 huevo entero y 4 claras de huevo\nEspinaca picada\nMínimo de aceite' },
  { name: 'Quesadillas de fajitas de pollo a la mexicana', mealType: 'lunch', ingredients: [{ query: 'Pechuga de pollo sin piel a la plancha', grams: 60 }, { query: 'Pimiento fresco', grams: 90 }, { query: 'Cebolla blanca rebanada', grams: 40 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Tortilla de harina', grams: 60 }], instructions: '60g de fajitas de pechuga de pollo\n1 taza de fajitas de pimientos y cebolla\nMínimo de aceite\n30g de queso oaxaca\n2 tortillas integrales' },
  { name: 'Tostadas con frijol y pavo asado', mealType: 'lunch', ingredients: [{ query: 'Tostada', grams: 30 }, { query: 'Frijoles refritos', grams: 45 }, { query: 'Jamón de pavo', grams: 42 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '3 tostadas horneadas con 1 cda de frijol c/u\n2 cdas de pavo deshebrado c/u\nLechuga o tomate\n1/4 de aguacate\nSalsa verde o roja' },
  { name: 'Waffles de avena', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 27 }, { query: 'Plátano', grams: 50 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Crema de cacahuate', grams: 30 }], instructions: '1/3 de hojuelas de avena\n1/2 plátano para la preparación\n1 huevo y 1/4 taza de claras\n1 cdita de vainilla y 1 pizca de canela\n1 cdita de cocoa en polvo\n5 disparos de aceite\nPara decorar: 2 cdas de crema de cacahuate o 10 almendras' },
  { name: 'Taco árabe', mealType: 'lunch', ingredients: [{ query: 'Pan pita', grams: 70 }, { query: 'Arrachera de res cocida', grams: 45 }, { query: 'Jitomate', grams: 70 }, { query: 'Hummus', grams: 30 }], instructions: '1 pan pita taquero\n45g de arrachera de res\n1 tomate\n2 cdas de hummus' },
  { name: 'Hot cakes de zanahoria', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 20 }, { query: 'Zanahoria rallada cruda', grams: 65 }, { query: 'Clara de huevo', grams: 66 }], instructions: '1/2 taza (20g) de avena molida\n2 cdas de leche de almendra\n1/2 zanahoria rallada\n2 claras de huevo\n1/4 cdita de polvo para hornear\n1 cdita de vainilla\n1 pizca de canela' },
  { name: 'Pan árabe relleno', mealType: 'lunch', ingredients: [{ query: 'Pan pita', grams: 35 }, { query: 'Pechuga de pollo sin piel cocida', grams: 30 }, { query: 'Jitomate', grams: 65 }, { query: 'Pimiento fresco', grams: 45 }], instructions: '1 pan pita cortado a la mitad\n30g de pollo deshebrado\n1/2 tomate y 1/2 pimiento\nSazonar con paprika y cebolla en polvo' },
  { name: 'Pastel de chocolate y nuez', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 20 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Plátano', grams: 50 }, { query: 'Nuez en mitades', grams: 10 }], instructions: '1/2 taza (20g) de avena molida\n2 cdas de leche de almendra\n2 claras de huevo\n1/4 cdita de polvo para hornear\n1 cdita de cacao en polvo\n1 cdita de vainilla\n1 pizca de canela\n1/2 plátano\n1 nuez troceada' },
  { name: 'Taco árabe de carne con costra de queso', mealType: 'lunch', ingredients: [{ query: 'Pan pita', grams: 70 }, { query: 'Queso Panela', grams: 30 }, { query: 'Jitomate', grams: 65 }, { query: 'Pimiento fresco', grams: 45 }, { query: 'Pechuga de pollo sin piel cocida', grams: 30 }], instructions: '1 pan pita\n30g de queso panela\n1/2 tomate y 1/2 pimiento amarillo\n1 cdita de aceite de oliva para aderezar\n30g de pechuga de pollo en cubos\nPaprika y cebolla en polvo' },
  { name: 'Kebab', mealType: 'lunch', ingredients: [{ query: 'Avena en hojuelas', grams: 27 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Pechuga de pollo sin piel a la plancha', grams: 90 }, { query: 'Queso Panela', grams: 20 }, { query: 'Aguacate Hass', grams: 31 }], instructions: 'Pan pita casero: 1/3 taza de avena, 3 claras de huevo, orégano y eneldo, 1 cda de polvo para hornear. Licuar y cocinar en el sartén.\nRelleno: 1 taza de verduras, 2 rebanadas de pechuga de pollo, 20g de queso panela, aguacate. Saltear las verduras y la pechuga con condimentos, colocar en el pan pita con el aguacate encima.' },
  { name: 'Portobellos caprese', mealType: 'snack', ingredients: [{ query: 'Hongo portobello crudo', grams: 30 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Jitomate', grams: 50 }], instructions: '30g de portobellos\n30g de queso oaxaca\nAlbahaca\nTomates rebanados\nLimpiar los portobellos, agregar el queso, los tomates y la albahaca encima, cocinar.' },
  { name: 'Tostadas de huevo a la mexicana', mealType: 'breakfast', ingredients: [{ query: 'Huevo entero fresco', grams: 88 }, { query: 'Jitomate', grams: 40 }, { query: 'Tostada de nopal horneada', grams: 20 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '2 huevos enteros revueltos con tomate, cebolla y chile serrano (dividir en las 2 tostadas)\n2 tostadas de nopal susalia\n1/4 de aguacate hass machacado (dividir en las 2 tostadas)\nInfusión de té verde' },
  { name: 'Hot cakes de avena y chocolate', mealType: 'breakfast', ingredients: [{ query: 'Clara de huevo', grams: 100 }, { query: 'Avena en hojuelas', grams: 27 }, { query: 'Leche de coco baja en calorías', grams: 25 }, { query: 'Fresas', grams: 60 }], instructions: '3 claras\n1/3 taza de avena en hojuelas\nRoyal, 1 cdita de vainilla, stevia, 1 chorrito de leche de coco (25 cal) y 1 cda de cocoa sin azúcar\nDecorar con 4 fresas rebanadas o 1/2 plátano\nMiel de maple sugar free y canela\nCafé americano con stevia' },
  { name: 'Enchiladas suizas', mealType: 'lunch', ingredients: [{ query: 'Tortilla de nopal', grams: 69 }, { query: 'Pechuga de pollo sin piel cocida', grams: 90 }, { query: 'Queso Panela', grams: 40 }], instructions: '3 piezas de tortilla de nopal susalia\n30g de pechuga de pollo deshebrada c/u (colocar en la plancha)\nBañar de salsa verde casera o doña chonita\n40g de queso panela derretido o 2 cdas de queso feta con aros de cebolla y 1 cda de fage\nInfusión de té verde' },
  { name: 'Steak de atún con ensalada', mealType: 'lunch', ingredients: [{ query: 'Atún en agua', grams: 100 }, { query: 'Espinaca cruda', grams: 40 }, { query: 'Queso Feta', grams: 20 }, { query: 'Aguacate Hass', grams: 31 }], instructions: '100g de steak de atún sellado con ajo picado, badia y salsa de soya bajo en sodio\n1 taza de ensalada: espinacas baby o lechuga, tomates cherry, 2 cdas de queso feta, aceite de oliva, sal rosa y jugo de limón\n4 galletas milton o 3 palitos integrales\n1/4 de aguacate hass\nIced tea' },
  { name: 'Flautas de pollo', mealType: 'lunch', ingredients: [{ query: 'Pechuga de pollo sin piel cocida', grams: 90 }, { query: 'Tortilla de nopal', grams: 69 }, { query: 'Queso Feta', grams: 20 }, { query: 'Col morada cruda', grams: 40 }, { query: 'Zanahoria rallada cruda', grams: 30 }], instructions: '30g de pechuga de pollo deshebrada c/u\n3 tortillas de nopal susalia (hacer taquitos y dorar)\nBañar de salsa verde casera o doña chonita, 1 cucharada de queso feta o fage y romanita\nEnsalada: col morada, zanahoria rallada, pepino, tomates cherry, espinacas, arúgula, berro\nAderezo: honey mustard light\nLimonada con stevia' },
  { name: 'Tacos de fajitas de pollo', mealType: 'lunch', ingredients: [{ query: 'Tortilla de nopal', grams: 46 }, { query: 'Pechuga de pollo sin piel a la plancha', grams: 90 }, { query: 'Pimiento fresco', grams: 90 }, { query: 'Hummus', grams: 15 }], instructions: '2 tortillas de nopal susalia\n45g de pechuga de pollo o res en fajitas c/u mezclado con pimiento morrón rojo, verde y cebolla\n1 cucharada de guacamole c/u\nPico de gallo\nSalsa verde o roja\n1 taza de ensalada: espinacas, tomates cherry, zanahoria rallada, pepino, limón, sal rosa, aceite de oliva y jengibre\nIced tea' },
  { name: 'Enchiladas suizas cremosas', mealType: 'lunch', ingredients: [{ query: 'Tortilla de maíz', grams: 50 }, { query: 'Pechuga de pollo sin piel cocida', grams: 60 }, { query: 'Yogur griego sin azúcar', grams: 45 }, { query: 'Queso Oaxaca', grams: 40 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Uva con semilla', grams: 45 }], instructions: '2 piezas de tortilla delgaditas\n30g de pollo deshebrado c/u\nLicuar salsa verde con 3 cdas de yogurt fage, 1 pizca de sal rosa\nDerretir 20g de queso Oaxaca light c/u\nEspinacas\nAros de cebolla cruda\n1 rebanada de aguacate hass delgada c/u\n9 uvas verdes\nInfusión de té verde con limón y stevia o café americano con leche de coco' },
  { name: 'Guacamole toast', mealType: 'breakfast', ingredients: [{ query: 'Pan thin', grams: 80 }, { query: 'Queso Cottage', grams: 30 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Clara de huevo', grams: 100 }], instructions: '2 piezas de pan thin\nDip de aguacate: 2 cdas de queso ricotta, 1/3 de aguacate hass, limón y salsa habanera yucateca o chiles chipotles, tomate y cebolla picada (dividir en las 2 tapas)\nEncima: 3 claras mezcladas con vegetales a elegir\nInfusión de té verde o café americano con leche de coco' },
  { name: 'Sweet toast', mealType: 'breakfast', ingredients: [{ query: 'Pan de caja integral', grams: 60 }, { query: 'Crema de cacahuate', grams: 10 }, { query: 'Fresas', grams: 40 }, { query: 'Arándano', grams: 30 }, { query: 'Granola con avena y miel', grams: 5 }], instructions: '2 piezas de pan daves\n2 cditas de crema de maní natural o de almendra\n4 fresas finamente picadas y 2 cdas de blueberries (dividir en los 2 panes)\n1 cdita de granola sin azúcar c/u\n1 chorrito de miel de maple sugar free c/u\nCapuccino: café americano con leche de coco' },
  { name: 'Hot cakes o waffles clásicos con Philadelphia y Nutella', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 27 }, { query: 'Clara de huevo', grams: 100 }, { query: 'Fresas', grams: 30 }, { query: 'Frambuesa', grams: 25 }, { query: 'Nutella de avellana', grams: 5 }], instructions: '1/3 taza de hojuelas de avena\n1 chorrito de leche de coco (25 cal)\n3 claras\nRoyal, stevia y canela (licuar todo)\n2 fresas en rebanadas y 4 piezas de frambuesas\n1 cdita de Philadelphia light y crema de avellana natural\n1 taza de café con leche de coco o agua natural' },
  { name: 'Cuernito con jamón y queso', mealType: 'breakfast', ingredients: [{ query: 'Cuernito', grams: 50 }, { query: 'Jamón de pavo', grams: 32 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Kiwi', grams: 70 }], instructions: '1 pieza de cuernito lite and light\n1.5 rebanadas de jamón de pechuga de pavo\n30g de queso Oaxaca light\nDip de chipotle: 2 cdas de yogurt fage, 1 cda de jugo de limón, 1 cda de salsa chipotle, sal de mar\n1 kiwi en cuadritos con 1 cda de coco rallado\nCafé americano con leche de coco' },
  { name: 'Tortilla española', mealType: 'breakfast', ingredients: [{ query: 'Tortilla de harina', grams: 30 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Jamón de pavo', grams: 21 }, { query: 'Queso Oaxaca', grams: 30 }], instructions: '1 pieza de tortilla de harina integral o 1 tortilla de maíz delgadita\nEncima: 1 huevo completo\nRellenar de: 1 rollito de jamón de pavo, 30g de queso Oaxaca light\nPor fuera: 1 cda de guacamole, salsa verde y roja, pico de gallo' },
  { name: 'Huevo hulk', mealType: 'breakfast', ingredients: [{ query: 'Clara de huevo', grams: 66 }, { query: 'Chorizo vegano', grams: 30 }, { query: 'Aguacate Hass', grams: 62 }, { query: 'Pan thin', grams: 40 }], instructions: '2 claras revueltas con tomate, cebolla, chile serrano y 2 cdas de chorizo vegano verde\n2 rebanadas de aguacate hass\nPan thin tostado (las 2 piezas)\nCapuccino: café americano con leche de coco' },
  { name: 'Hot cakes o waffles estilo tiramisú', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 27 }, { query: 'Clara de huevo', grams: 100 }, { query: 'Queso Ricotta', grams: 45 }, { query: 'Yogur griego sin azúcar', grams: 30 }, { query: 'Plátano', grams: 50 }], instructions: '1/3 taza de hojuelas de avena\n1 chorrito de leche de coco (25 cal)\n3 claras\nCocoa sin azúcar, royal, stevia y canela (licuar todo)\nPreparar los hot cakes e intercalar con: 3 cdas de queso ricotta, 2 cdas de fage, endulzado con stevia\nJarabe de café: 2 cditas de café soluble, cocoa sin azúcar con leche de coco (mezclar)\nTopping: 1/2 plátano en rebanadas y canela. Capuccino con leche de coco.' },
  { name: 'Hot cakes de chocolate o matcha con betún', mealType: 'breakfast', ingredients: [{ query: 'Avena en hojuelas', grams: 27 }, { query: 'Clara de huevo', grams: 100 }, { query: 'Yogur griego sin azúcar', grams: 120 }, { query: 'Frambuesa', grams: 40 }], instructions: '1/3 taza de harina de avena, 3 claras, royal, canela, 1 chorrito de leche de coco, cacao sin azúcar o 1 cdita de matcha, stevia\nBetún: 1/2 taza de yogurt fage, 1 chorrito de miel de maple sugar free o stevia (mezclar)\n1/3 taza de mix de frutos rojos o 1/2 plátano\nCafé americano con leche de coco' },
  { name: 'Quesadilla con tomates deshidratados y champiñones al ajillo', mealType: 'lunch', ingredients: [{ query: 'Pan pita', grams: 35 }, { query: 'Queso Oaxaca', grams: 40 }, { query: 'Champiñón crudo rebanado', grams: 40 }, { query: 'Jitomate deshidratado', grams: 15 }], instructions: '1/2 pieza de pan pita libanius\n40g de queso Oaxaca light mezclado con tomates deshidratados y champiñones al ajillo\n2 cdas de guacamole\nSalsa verde y salsa roja al gusto\nGerminado de alfalfa' },
  { name: 'Huevos rancheros', mealType: 'breakfast', ingredients: [{ query: 'Tostada de nopal horneada', grams: 20 }, { query: 'Frijoles refritos', grams: 30 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Jitomate', grams: 40 }], instructions: '2 tostadas de nopal susalia o de maíz sanissimo\n1 cdita de frijol bajo en grasa c/u\n2 claras de huevo (dividir en las 2 tostadas) con 30g de queso Oaxaca light derretido, tomate, cebolla y chile serrano\nBañar de salsa roja mexicana ambas tostadas' },
  { name: 'French toast roll ups', mealType: 'breakfast', ingredients: [{ query: 'Pan de caja integral', grams: 55 }, { query: 'Fresas', grams: 40 }, { query: 'Crema de cacahuate', grams: 10 }, { query: 'Clara de huevo', grams: 100 }], instructions: '2 piezas de pan daves killer bread sin orilla y aplanados\n2 fresas en cachitos c/u\n2 cditas de crema de avellana natural c/u\nEnrollar. Mezcla: 3 claras, leche de coco, canela, vainilla y stevia, remojar y cocinar en la plancha\nCapuccino: café americano con leche de coco' },
  { name: 'Huevos motuleños con plátano macho', mealType: 'breakfast', ingredients: [{ query: 'Tostada', grams: 40 }, { query: 'Huevo entero fresco', grams: 44 }, { query: 'Frijoles refritos', grams: 30 }, { query: 'Jamón de pavo', grams: 21 }, { query: 'Chícharo', grams: 25 }, { query: 'Plátano Macho', grams: 30 }], instructions: '2 tostadas delgaditas en cachitos\n1 huevo estrellado\n2 cucharadas de frijol bajo en grasa\nSalsa de tomate casera con 1 rebanada de jamón de pechuga de pavo en cuadritos\n1 cucharada de chícharos\n1 rebanada de plátano macho a la parrilla' },
  { name: 'Tostadas francesas rellenas de fit mix, frutos rojos y yogurt', mealType: 'breakfast', ingredients: [{ query: 'Pan de caja integral', grams: 55 }, { query: 'Clara de huevo', grams: 100 }, { query: 'Fresas', grams: 30 }, { query: 'Arándano', grams: 30 }, { query: 'Yogur griego sin azúcar', grams: 15 }], instructions: '2 piezas de pan daves killer bread, rellenar con 1 cda de fit mix c/u (doblar)\nMezcla: 3 claras, leche de coco, canela, vainilla y stevia\nRemojar los panes rellenos y colocarlos en la sartén\n1 cda de frutos rojos c/u\n1 cda de yogurt griego sin azúcar con stevia c/u\nCanela espolvoreada' },
  { name: 'Burrito o tacos de huevo a la mexicana y frijol', mealType: 'breakfast', ingredients: [{ query: 'Pan pita', grams: 35 }, { query: 'Clara de huevo', grams: 66 }, { query: 'Frijoles refritos', grams: 30 }, { query: 'Uva con semilla', grams: 45 }], instructions: '1/2 pieza de pan pita libanius o 2 tortillas de avena o maíz delgaditas\n2 claras mezcladas con tomate, cebolla y chile serrano\n1 cda de frijol bajo en grasa c/u\nChiles chipotles\n9 uvas verdes o 1 kiwi en rebanadas\nAgua natural o limonada con stevia o capuccino con leche de coco' },
  { name: 'Tartaras', mealType: 'breakfast', ingredients: [{ query: 'Pan thin', grams: 40 }, { query: 'Frijoles refritos', grams: 15 }, { query: 'Jamón de pavo', grams: 21 }, { query: 'Queso Mozzarella', grams: 40 }, { query: 'Aguacate Hass', grams: 31 }], instructions: 'Pan thin\n1 cda de frijol bajo en grasa c/u\n1 rebanada de pechuga de pavo c/u\n40g de queso mozzarella gratinado c/u\nSalsa roja, salsa verde\n1 rebanada de aguacate hass\nPico de gallo\nCapuccino: café americano con leche de coco' },
  { name: 'Quesadilla buffalo con guacamole', mealType: 'lunch', ingredients: [{ query: 'Tortilla de harina', grams: 50 }, { query: 'Queso Oaxaca', grams: 30 }, { query: 'Champiñón crudo rebanado', grams: 30 }, { query: 'Aguacate Hass', grams: 31 }, { query: 'Yogur griego sin azúcar', grams: 5 }], instructions: '2 tortillas delgaditas\n30g de queso Oaxaca light mezclado con champiñones c/u\n1 cda de guacamole c/u\n1 chorrito de salsa buffalo\nEspinacas\n1 cdita de yogurt griego sin azúcar c/u\nInfusión de té verde con limón y stevia' },
  { name: 'Smoothie bowl', mealType: 'breakfast', ingredients: [{ query: 'Yogur griego sin azúcar', grams: 90 }, { query: 'Granola con avena y miel', grams: 20 }, { query: 'Plátano', grams: 50 }, { query: 'Fresas', grams: 60 }], instructions: '90g de yogurt griego mezclado con cacao y stevia\n3 cdas de granola artesanal de avena\n1/2 plátano\n2 fresas en rebanadas\nCapuccino: café americano con leche de coco o agua natural' },
]

async function findIngredient(query) {
  return prisma.ingredient.findFirst({ where: { practiceId, name: { contains: query, mode: 'insensitive' } }, orderBy: { name: 'asc' } })
}

async function ensureFallbackIngredients() {
  for (const item of FALLBACK_INGREDIENTS) {
    const existing = await prisma.ingredient.findFirst({ where: { practiceId, name: item.name } })
    if (!existing) await prisma.ingredient.create({ data: { practiceId, ...item } })
  }
}

async function main() {
  await ensureFallbackIngredients()

  const misses = []
  let createdCount = 0
  let updatedCount = 0

  for (const recipe of RECIPES) {
    const resolved = []
    for (const line of recipe.ingredients) {
      const ingredient = await findIngredient(line.query)
      if (!ingredient) { misses.push(`${recipe.name}: "${line.query}"`); continue }
      resolved.push({ ingredientId: ingredient.id, quantity: line.grams, unit: 'g', equivalence: null })
    }
    if (!resolved.length) { misses.push(`${recipe.name}: SIN INGREDIENTES RESUELTOS, se omite`); continue }

    const existing = await prisma.recipe.findFirst({ where: { practiceId, name: recipe.name } })
    let saved
    if (existing) {
      await prisma.recipeIngredient.deleteMany({ where: { recipeId: existing.id } })
      saved = await prisma.recipe.update({ where: { id: existing.id }, data: { mealTypes: [recipe.mealType], instructions: recipe.instructions, ingredients: { create: resolved } }, include: { ingredients: { include: { ingredient: true } } } })
      updatedCount += 1
    } else {
      saved = await prisma.recipe.create({ data: { practiceId, name: recipe.name, mealTypes: [recipe.mealType], portions: 1, instructions: recipe.instructions, nutrition: {}, restrictions: [], ingredients: { create: resolved } }, include: { ingredients: { include: { ingredient: true } } } })
      createdCount += 1
    }

    const totals = { kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 0, vitaminA: 0, vitaminC: 0, folicAcid: 0, calcium: 0, iron: 0, vitaminD: 0, vitaminE: 0, vitaminK: 0, vitaminB12: 0, zinc: 0, iodine: 0, selenium: 0 }
    for (const item of saved.ingredients) {
      const nutrition = item.ingredient.nutrition || {}
      const factor = Number(item.quantity) / 100
      for (const key of Object.keys(totals)) totals[key] += Number(nutrition[key] || 0) * factor
    }
    const nutrition = Object.fromEntries(Object.entries(totals).map(([key, value]) => [key, Math.round(value * 10) / 10]))
    await prisma.recipe.update({ where: { id: saved.id }, data: { nutrition, version: { increment: 1 } } })
  }

  console.log(`Recetas: ${createdCount} nuevas, ${updatedCount} actualizadas.`)
  if (misses.length) {
    console.log(`\nIngredientes sin match (${misses.length}), revisar a mano:`)
    for (const miss of misses) console.log(' -', miss)
  }
}

main().catch((error) => { console.error(error); process.exitCode = 1 }).finally(() => prisma.$disconnect())
