import Icon from './Icon.jsx'
import { navItems } from '../app/navItems.js'
import { useAuth } from '../lib/AuthContext.jsx'

const ROLE_LABELS = { OWNER: 'Propietaria', NUTRITIONIST: 'Nutrióloga', ASSISTANT: 'Asistente' }

export default function AppChrome({ active, setActive, children }) {
  const { user, practice, logout } = useAuth()
  const initials = user ? user.name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() : '··'
  const roleLabel = user ? ROLE_LABELS[user.role] || user.role : ''
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">N</div><div><strong>nutri<span>·</span>studio</strong><small>CLINICAL WORKSPACE</small></div></div><div className="workspace"><span className="avatar small">{initials}</span><div style={{ minWidth: 0 }}><b style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{user?.name || 'Cargando…'}</b><small style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{practice?.name || 'Consulta privada'}</small></div><span className="chevron">⌄</span></div><div className="nav-label">Tu espacio</div><nav>{navItems.map(([icon, label]) => <button key={label} className={active === label ? 'nav-item active' : 'nav-item'} onClick={() => setActive(label)}><Icon>{icon}</Icon>{label}{label === 'Pacientes' && <span className="nav-count">24</span>}</button>)}</nav><div className="nav-label library-label">Biblioteca</div><button className={active === 'Educación' ? 'nav-item active' : 'nav-item'} onClick={() => setActive('Educación')}><Icon>♡</Icon>Educación</button><button className="nav-item"><Icon>⚙</Icon>Configuración</button><div className="sidebar-footer"><div className="plan-tag"><span className="spark">✦</span><div><b>Plan profesional</b><small>Tu periodo termina en 18 días</small></div></div><button className="help">? <span>Centro de ayuda</span></button></div></aside><main className="main"><header className="topbar"><div className="crumb"><span>Tu espacio</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><button className="icon-button">⌕</button><button className="icon-button notification">♧<i /></button><span className="divider" /><button className="icon-button" title="Cerrar sesión" onClick={logout} style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span className="avatar">{initials}</span><div className="user-name"><b>{user?.name || 'Cargando…'}</b><small>{roleLabel}</small></div><span className="chevron">⌄</span></button></div></header>{children}</main></div>
} 
