import Icon from './Icon.jsx'
import { navGroups } from '../app/navItems.js'
import { useAuth } from '../lib/AuthContext.jsx'

const ROLE_LABELS = { OWNER: 'Propietaria', NUTRITIONIST: 'Nutrióloga', ASSISTANT: 'Asistente' }

export default function AppChrome({ active, setActive, children }) {
  const { user, practice, logout } = useAuth()
  const initials = user ? user.name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() : '··'
  const roleLabel = user ? ROLE_LABELS[user.role] || user.role : ''
  return <div className="app-shell"><aside className="pc-sidebar"><button type="button" className="pc-brand" onClick={() => setActive('Hoy')} title="Ir a Hoy"><div className="brand-mark">N</div><div><strong>nutri<span>·</span>studio</strong><small>CLINICAL WORKSPACE</small></div></button><div className="pc-workspace"><span className="avatar small">{initials}</span><div style={{ minWidth: 0 }}><b style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{user?.name || 'Cargando…'}</b><small style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{practice?.name || 'Consulta privada'}</small></div><span className="chevron">⌄</span></div><div className="pc-navbar">{navGroups.map((group) => <div className="pc-nav-group" key={group.label}><div className="pc-caption">{group.label}</div><nav>{group.items.map(([icon, label]) => <button key={label} className={active === label ? 'pc-link active' : 'pc-link'} onClick={() => setActive(label)}><span className="pc-micon"><Icon>{icon}</Icon></span><span className="pc-mtext">{label}</span>{label === 'Pacientes' && <span className="pc-badge">24</span>}</button>)}</nav></div>)}<button className={active === 'Configuración' ? 'pc-link pc-settings-link active' : 'pc-link pc-settings-link'} onClick={() => setActive('Configuración')}><span className="pc-micon"><Icon>⚙</Icon></span><span className="pc-mtext">Configuración</span></button></div><div className="pc-sidebar-footer"><div className="plan-tag"><span className="spark">✦</span><div><b>Plan profesional</b><small>Tu periodo termina en 18 días</small></div></div><button className="help">? <span>Centro de ayuda</span></button></div></aside><main className="main"><header className="pc-header"><div className="crumb"><span>Tu espacio</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><button className="icon-button">⌕</button><button className="icon-button notification">♧<i /></button><span className="divider" /><button className="icon-button" title="Cerrar sesión" onClick={logout} style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span className="avatar">{initials}</span><div className="user-name"><b>{user?.name || 'Cargando…'}</b><small>{roleLabel}</small></div><span className="chevron">⌄</span></button></div></header>{children}</main></div>
}
