// Curated food table for auto-linking the 500-recipe book. Two jobs:
//  1. Canonicalize messy free-text terms ("jitomates", "caldo pollo gluten", "eritritol stevia
//     granulada ajusta") to a known food via `aliases`.
//  2. Provide approximate per-100 g values when the food is missing from the SMAE catalog, so the
//     "Aproximados Menu 500" group can fill it and the recipe still gets a calculated value.
//
// Values are approximate references (USDA/SMAE-style averages), not lab data — this is for
// contrasting against the book's numbers, which are approximations too.

export const APPROX_GROUP = 'Aproximados Menu 500'

// [key, name, kcal, protein, carbs, fat, fiber, category, ...aliases]
const F = (key, name, kcal, protein, carbs, fat, fiber, category, aliases) => ({ key, name, kcal, protein, carbs, fat, fiber, category, aliases })

export const FOODS = [
  F('huevo', 'Huevo', 143, 12.6, 0.7, 9.5, 0, 'AOA MBAG', ['huevo entero', 'huevo', 'huevos']),
  F('clara', 'Clara de huevo', 52, 10.9, 0.7, 0.2, 0, 'AOA MBAG', ['clara de huevo', 'claras de huevo', 'clara', 'claras']),
  F('yema', 'Yema de huevo', 322, 15.9, 3.6, 26.5, 0, 'AOA MAG', ['yema', 'yemas']),
  F('pollo', 'Pechuga de pollo', 165, 31, 0, 3.6, 0, 'AOA MBAG', ['pechuga de pollo', 'pechuga pollo', 'pechugas pollo', 'pollo deshebrado', 'pollo', 'pechuga']),
  F('pavo', 'Pechuga de pavo', 135, 29, 0, 1, 0, 'AOA MBAG', ['pechuga de pavo', 'pavo']),
  F('jamon', 'Jamón de pavo', 120, 18, 2, 4, 0, 'AOA MBAG', ['jamon de pavo', 'jamon']),
  F('res', 'Bistec de res', 150, 26, 0, 4.5, 0, 'AOA MBAG', ['bistec de res', 'bistec', 'carne de res', 'carne res', 'res', 'arrachera']),
  F('molida', 'Carne molida de res', 220, 24, 0, 13, 0, 'AOA MAG', ['carne molida', 'molida de res', 'molida']),
  F('cerdo', 'Carne de cerdo', 242, 27, 0, 14, 0, 'AOA MAG', ['carne de cerdo', 'cerdo', 'puerco', 'carnitas']),
  F('atun', 'Atún en agua', 116, 26, 0, 1, 0, 'AOA MBAG', ['atun en agua', 'atun']),
  F('salmon', 'Salmón', 208, 20, 0, 13, 0, 'AOA AAG', ['salmon']),
  F('pescado', 'Pescado blanco', 100, 20, 0, 2, 0, 'AOA MBAG', ['filete de pescado', 'pescado blanco', 'pescado', 'tilapia', 'marlin']),
  F('camaron', 'Camarón', 99, 24, 0.2, 0.3, 0, 'AOA MBAG', ['camaron', 'camarones']),
  F('chorizo', 'Chorizo', 455, 24, 2, 38, 0, 'AOA AAG', ['chorizo']),
  F('tocino', 'Tocino', 541, 37, 1, 42, 0, 'AOA AAG', ['tocino']),
  F('tofu', 'Tofu', 76, 8, 2, 5, 1, 'Leguminosas', ['tofu']),
  F('soya', 'Soya texturizada', 336, 50, 30, 1, 18, 'Leguminosas', ['soya texturizada', 'proteina de soya', 'soya']),
  F('panela', 'Queso Panela', 220, 22, 3.5, 13.5, 0, 'AOA BAG', ['queso panela', 'panela']),
  F('oaxaca', 'Queso Oaxaca', 280, 24, 3, 20, 0, 'AOA BAG', ['queso oaxaca', 'oaxaca']),
  F('crema', 'Queso crema', 342, 6, 4, 34, 0, 'Grasas con proteínas', ['queso crema', 'queso filadelfia', 'filadelfia']),
  F('cottage', 'Queso cottage', 98, 11, 3.4, 4.3, 0, 'AOA MBAG', ['queso cottage', 'cottage', 'requeson', 'jocoque']),
  F('feta', 'Queso Feta', 264, 14, 4, 21, 0, 'AOA BAG', ['queso feta', 'feta']),
  F('mozzarella', 'Queso Mozzarella', 280, 28, 3, 17, 0, 'AOA BAG', ['queso mozzarella', 'mozzarella']),
  F('parmesano', 'Queso Parmesano', 431, 38, 4, 29, 0, 'AOA BAG', ['queso parmesano', 'parmesano']),
  F('quesovegano', 'Queso vegano', 250, 1, 20, 18, 0, 'AOA BAG', ['queso vegano', 'queso vegetal', 'queso sin lactosa', 'queso bajo en lactosa', 'queso lactosa']),
  F('yogur', 'Yogur griego sin azúcar', 59, 10, 3.6, 0.4, 0, 'Leche descremada', ['yogur griego', 'yogur', 'yoghurt']),
  F('yogurveg', 'Yogur vegetal', 60, 3, 6, 3, 0, 'Leche descremada', ['yogur vegetal', 'yogur de coco', 'yogur de almendra']),
  F('lechealmendra', 'Leche de almendras sin azúcar', 17, 0.6, 0.6, 1.5, 0.3, 'Leche descremada', ['leche de almendras', 'leche almendras', 'bebida de almendra']),
  F('lechecoco', 'Leche de coco sin azúcar', 31, 0.2, 3, 2, 0, 'Leche descremada', ['leche de coco', 'leche coco', 'bebida de coco']),
  F('lechesoya', 'Leche de soya', 54, 3.3, 6, 1.8, 0.5, 'Leche descremada', ['leche de soya', 'leche soya']),
  F('cremacoco', 'Crema de coco', 230, 2.3, 6, 23, 0, 'Grasas con proteínas', ['crema de coco', 'crema coco']),
  F('cremabatir', 'Crema para batir', 340, 2, 3, 36, 0, 'Grasas con proteínas', ['crema para batir', 'crema batida', 'crema batir']),
  F('aceiteoliva', 'Aceite de oliva', 884, 0, 0, 100, 0, 'Grasas sin proteínas', ['aceite de oliva', 'aceite oliva', 'oliva']),
  F('aceitecoco', 'Aceite de coco', 862, 0, 0, 100, 0, 'Grasas sin proteínas', ['aceite de coco', 'aceite coco']),
  F('aceite', 'Aceite vegetal', 884, 0, 0, 100, 0, 'Grasas sin proteínas', ['aceite vegetal', 'aceite neutro', 'aceite comestible', 'aceite']),
  F('mantequilla', 'Mantequilla', 717, 0.9, 0.1, 81, 0, 'Grasas con proteínas', ['mantequilla', 'mantequilla ghee', 'ghee']),
  F('mantequillaveg', 'Mantequilla vegetal', 700, 0, 0, 78, 0, 'Grasas sin proteínas', ['mantequilla vegetal', 'margarina']),
  F('cremacacahuate', 'Crema de cacahuate', 588, 25, 20, 50, 6, 'Grasas con proteínas', ['crema de cacahuate', 'crema de mani', 'mantequilla de cacahuate', 'crema de almendra']),
  F('aguacate', 'Aguacate', 160, 2, 9, 15, 6.7, 'Grasas sin proteínas', ['aguacate', 'aguacates', 'guacamole']),
  F('aceituna', 'Aceituna', 115, 0.8, 6, 11, 3, 'Grasas sin proteínas', ['aceituna', 'aceitunas', 'alcaparra', 'alcaparras']),
  F('almendra', 'Almendra', 579, 21, 22, 50, 12.5, 'Grasas con proteínas', ['almendra', 'almendras']),
  F('nuez', 'Nuez', 654, 15, 14, 65, 6.7, 'Grasas con proteínas', ['nuez', 'nueces']),
  F('cacahuate', 'Cacahuate', 567, 26, 16, 49, 8.5, 'Grasas con proteínas', ['cacahuate', 'cacahuates', 'mani']),
  F('chia', 'Semilla de chía', 486, 17, 42, 31, 34, 'Grasas con proteínas', ['semilla de chia', 'semillas de chia', 'chia']),
  F('linaza', 'Linaza', 534, 18, 29, 42, 27, 'Grasas con proteínas', ['linaza', 'semilla de linaza', 'semillas de linaza']),
  F('psyllium', 'Psyllium', 200, 2, 80, 1, 70, 'Cereales S/G', ['psyllium', 'cascara de psyllium']),
  F('coco', 'Coco', 354, 3.3, 15, 33, 9, 'Grasas con proteínas', ['coco rallado', 'coco tostado', 'coco']),
  F('harinaalmendra', 'Harina de almendras', 590, 21, 22, 50, 12, 'Cereales C/G', ['harina de almendras', 'harina almendras', 'harina de almendra']),
  F('harinacoco', 'Harina de coco', 400, 15, 60, 15, 38, 'Cereales C/G', ['harina de coco', 'harina coco']),
  F('harinaarroz', 'Harina de arroz', 360, 6, 80, 1, 2.4, 'Cereales S/G', ['harina de arroz', 'harina arroz']),
  F('harinamaiz', 'Harina de maíz', 361, 7, 76, 3.9, 3, 'Cereales S/G', ['harina de maiz', 'harina maiz', 'masa harina']),
  F('harinaavena', 'Harina de avena', 389, 17, 66, 7, 10.6, 'Cereales S/G', ['harina de avena', 'harina avena']),
  F('fecula', 'Fécula de maíz', 381, 0.3, 91, 0.1, 0.9, 'Cereales S/G', ['fecula de maiz', 'maicena', 'fecula']),
  F('avena', 'Avena', 389, 17, 66, 7, 10.6, 'Cereales S/G', ['avena en hojuelas', 'hojuelas de avena', 'avena']),
  F('arroz', 'Arroz cocido', 130, 2.7, 28, 0.3, 0.4, 'Cereales S/G', ['arroz']),
  F('quinoa', 'Quinoa cocida', 120, 4.4, 21, 1.9, 2.8, 'Cereales S/G', ['quinoa']),
  F('amaranto', 'Amaranto', 102, 4, 19, 1.6, 2, 'Cereales S/G', ['amaranto']),
  F('tortillamaiz', 'Tortilla de maíz', 218, 5.7, 45, 2.9, 6.3, 'Cereales S/G', ['tortillas de maiz', 'tortilla de maiz', 'tortillas maiz', 'tortilla maiz', 'tortillas', 'tortilla']),
  F('tortillaharina', 'Tortilla de harina', 300, 8, 51, 7, 2, 'Cereales C/G', ['tortilla de harina', 'tortilla harina']),
  F('tortillanopal', 'Tortilla de nopal', 60, 2, 12, 0.5, 4, 'Cereales S/G', ['tortilla de nopal', 'tortillas de nopal']),
  F('tostada', 'Tostada', 400, 8, 70, 10, 6, 'Cereales C/G', ['tostada', 'tostadas']),
  F('pan', 'Pan', 265, 9, 49, 3.2, 2.7, 'Cereales S/G', ['pan de caja', 'pan integral', 'pan', 'pan pita', 'pita']),
  F('masa', 'Masa de maíz', 218, 5, 45, 3, 4, 'Cereales S/G', ['masa de maiz', 'masa nixtamalizada', 'masa', 'arepa', 'arepas']),
  F('granola', 'Granola', 462, 11, 67, 19, 7, 'Cereales C/G', ['granola']),
  F('galleta', 'Galleta', 450, 7, 70, 16, 3, 'Cereales C/G', ['galleta', 'galletas', 'bizcocho', 'pan dulce', 'cuernito', 'croissant', 'base para pay', 'obleas']),
  F('polvohornear', 'Polvo para hornear', 150, 0, 36, 0, 0, 'Azucares sin grasa', ['polvo para hornear', 'polvo hornear', 'royal', 'levadura']),
  F('grenetina', 'Grenetina sin sabor', 335, 86, 0, 0.1, 0, 'Libres en energía', ['grenetina', 'gelatina sin sabor']),
  F('gelatina', 'Gelatina', 60, 1.2, 14, 0, 0, 'Azucares sin grasa', ['gelatina']),
  F('endulzante', 'Endulzante sin calorías', 0, 0, 0, 0, 0, 'Libres en energía', ['eritritol', 'xilitol', 'stevia', 'sucralosa', 'splenda', 'endulzante', 'monk fruit', 'alulosa', 'endulcorante']),
  F('miel', 'Miel', 304, 0.3, 82, 0, 0, 'Azucares sin grasa', ['miel de maple', 'miel de abeja', 'jarabe', 'miel']),
  F('azucar', 'Azúcar', 387, 0, 100, 0, 0, 'Azucares sin grasa', ['azucar', 'azucar refinada', 'piloncillo']),
  F('datil', 'Dátil', 282, 2.5, 75, 0.4, 8, 'Frutas', ['datil', 'datiles']),
  F('cajeta', 'Cajeta sin azúcar', 250, 6, 45, 7, 0, 'Azucares con grasa', ['cajeta']),
  F('chocolate', 'Chocolate sin azúcar', 500, 10, 30, 38, 10, 'Azucares con grasa', ['chocolate oscuro', 'chocolate sin azucar', 'chispas de chocolate', 'chocolate']),
  F('cocoa', 'Cocoa en polvo', 228, 20, 58, 14, 33, 'Azucares sin grasa', ['cocoa en polvo', 'cacao en polvo', 'cocoa', 'cacao']),
  F('caldopollo', 'Caldo de pollo', 5, 0.9, 0.5, 0.1, 0, 'Libres en energía', ['caldo de pollo', 'caldo pollo', 'consome de pollo']),
  F('caldores', 'Caldo de res', 5, 0.9, 0.5, 0.1, 0, 'Libres en energía', ['caldo de res', 'caldo res']),
  F('caldoverduras', 'Caldo de verduras', 5, 0.5, 1, 0.1, 0, 'Libres en energía', ['caldo de verduras', 'caldo verduras']),
  F('salsa', 'Salsa', 30, 1, 6, 0.2, 1, 'Verduras', ['salsa verde', 'salsa roja', 'salsa picante', 'salsa']),
  F('mostaza', 'Mostaza', 60, 4, 6, 3, 2, 'Grasas sin proteínas', ['mostaza']),
  F('vinagre', 'Vinagre', 20, 0, 0.6, 0, 0, 'Libres en energía', ['vinagre']),
  F('soyaSauce', 'Salsa de soya', 60, 8, 6, 1, 1, 'Libres en energía', ['salsa de soya', 'salsa soya']),
  F('jerez', 'Alcohol', 231, 0, 3, 0, 0, 'Alcohol', ['vino', 'tequila', 'ron']),
  F('jitomate', 'Jitomate', 18, 0.9, 3.9, 0.2, 1.2, 'Verduras', ['jitomate', 'jitomates', 'tomate rojo', 'tomate']),
  F('tomatillo', 'Tomate verde', 21, 1, 4, 0.2, 1.5, 'Verduras', ['tomate verde', 'tomatillo', 'tomatillos']),
  F('cebolla', 'Cebolla', 40, 1.1, 9.3, 0.1, 1.7, 'Verduras', ['cebolla blanca', 'cebolla morada', 'cebolla', 'cebollitas']),
  F('ajo', 'Ajo', 149, 6.4, 33, 0.5, 2.1, 'Verduras', ['ajo', 'ajos']),
  F('cilantro', 'Cilantro', 23, 2.1, 3.7, 0.5, 2.8, 'Verduras', ['cilantro']),
  F('espinaca', 'Espinaca', 23, 2.9, 3.6, 0.4, 2.2, 'Verduras', ['espinaca', 'espinacas']),
  F('lechuga', 'Lechuga', 15, 1.4, 2.9, 0.2, 1.3, 'Verduras', ['lechuga', 'arugula', 'arugula', 'berro']),
  F('nopal', 'Nopal', 16, 1.3, 3.3, 0.1, 2.2, 'Verduras', ['nopal', 'nopales']),
  F('zanahoria', 'Zanahoria', 41, 0.9, 10, 0.2, 2.8, 'Verduras', ['zanahoria', 'zanahorias']),
  F('calabacita', 'Calabacita', 17, 1.2, 3.1, 0.3, 1, 'Verduras', ['calabacita', 'calabacitas', 'calabacin']),
  F('pimiento', 'Pimiento', 26, 1, 6, 0.3, 2.1, 'Verduras', ['pimiento morron', 'pimiento', 'pimientos']),
  F('chileserrano', 'Chile serrano', 32, 1.8, 6.7, 0.4, 1.5, 'Verduras', ['chile serrano', 'serrano']),
  F('chilepoblano', 'Chile poblano', 20, 0.9, 4.6, 0.2, 1.8, 'Verduras', ['chile poblano', 'poblano', 'rajas']),
  F('chileguajillo', 'Chile guajillo', 110, 3.5, 22, 3, 8, 'Verduras', ['chile guajillo', 'guajillo']),
  F('chileancho', 'Chile ancho', 110, 3.5, 22, 3, 8, 'Verduras', ['chile ancho', 'ancho']),
  F('chilepasilla', 'Chile pasilla', 110, 3.5, 22, 3, 8, 'Verduras', ['chile pasilla', 'pasilla']),
  F('chilechipotle', 'Chile chipotle', 100, 4, 15, 2, 5, 'Verduras', ['chile chipotle', 'chipotle', 'chipotles']),
  F('champinon', 'Champiñón', 22, 3.1, 3.3, 0.3, 1, 'Verduras', ['champinon', 'champinones', 'hongo', 'hongos', 'setas', 'portobello', 'portobellos']),
  F('pepino', 'Pepino', 15, 0.7, 3.6, 0.1, 0.5, 'Verduras', ['pepino', 'pepinos']),
  F('apio', 'Apio', 16, 0.7, 3, 0.2, 1.6, 'Verduras', ['apio']),
  F('col', 'Col', 25, 1.3, 6, 0.1, 2.5, 'Verduras', ['col morada', 'col', 'repollo']),
  F('coliflor', 'Coliflor', 25, 1.9, 5, 0.3, 2, 'Verduras', ['coliflor']),
  F('brocoli', 'Brócoli', 34, 2.8, 6.6, 0.4, 2.6, 'Verduras', ['brocoli']),
  F('ejote', 'Ejote', 31, 1.8, 7, 0.2, 3.4, 'Verduras', ['ejote', 'ejotes']),
  F('chicharo', 'Chícharo', 81, 5.4, 14, 0.4, 5, 'Leguminosas', ['chicharo', 'chicharos', 'arveja']),
  F('elote', 'Elote', 86, 3.2, 19, 1.2, 2.7, 'Cereales S/G', ['elote', 'maiz tierno']),
  F('betabel', 'Betabel', 43, 1.6, 10, 0.2, 2.8, 'Verduras', ['betabel']),
  F('jicama', 'Jícama', 38, 0.7, 9, 0.1, 4.9, 'Verduras', ['jicama']),
  F('florcalabaza', 'Flor de calabaza', 15, 1.5, 3, 0.1, 1, 'Verduras', ['flor de calabaza']),
  F('huitlacoche', 'Huitlacoche', 40, 3, 7, 1, 2, 'Verduras', ['huitlacoche']),
  F('verdolaga', 'Verdolaga', 20, 2, 3.4, 0.4, 1.5, 'Verduras', ['verdolaga', 'verdolagas']),
  F('huauzontle', 'Huauzontle', 30, 3, 5, 0.5, 2, 'Verduras', ['huauzontle', 'huauzontles']),
  F('papa', 'Papa', 77, 2, 17, 0.1, 2.2, 'Cereales S/G', ['papa', 'papas']),
  F('camote', 'Camote', 86, 1.6, 20, 0.1, 3, 'Cereales S/G', ['camote', 'batata']),
  F('platano', 'Plátano', 89, 1.1, 23, 0.3, 2.6, 'Frutas', ['platano macho', 'platano', 'platanos', 'banana']),
  F('manzana', 'Manzana', 52, 0.3, 14, 0.2, 2.4, 'Frutas', ['manzana', 'manzanas']),
  F('pera', 'Pera', 57, 0.4, 15, 0.1, 3.1, 'Frutas', ['pera', 'peras']),
  F('naranja', 'Naranja', 47, 0.9, 12, 0.1, 2.4, 'Frutas', ['naranja', 'naranjas']),
  F('mandarina', 'Mandarina', 53, 0.8, 13, 0.3, 1.8, 'Frutas', ['mandarina']),
  F('fresa', 'Fresa', 32, 0.7, 7.7, 0.3, 2, 'Frutas', ['fresa', 'fresas']),
  F('arandano', 'Arándano', 57, 0.7, 14, 0.3, 2.4, 'Frutas', ['arandano', 'arandanos', 'blueberry', 'blueberries']),
  F('frambuesa', 'Frambuesa', 52, 1.2, 12, 0.7, 6.5, 'Frutas', ['frambuesa', 'frambuesas', 'frutos rojos']),
  F('zarzamora', 'Zarzamora', 43, 1.4, 10, 0.5, 5.3, 'Frutas', ['zarzamora', 'zarzamoras', 'mora']),
  F('mango', 'Mango', 60, 0.8, 15, 0.4, 1.6, 'Frutas', ['mango', 'mangos']),
  F('pina', 'Piña', 50, 0.5, 13, 0.1, 1.4, 'Frutas', ['pina', 'anana']),
  F('uva', 'Uva', 69, 0.7, 18, 0.2, 0.9, 'Frutas', ['uva', 'uvas']),
  F('kiwi', 'Kiwi', 61, 1.1, 15, 0.5, 3, 'Frutas', ['kiwi']),
  F('durazno', 'Durazno', 39, 0.9, 10, 0.3, 1.5, 'Frutas', ['durazno', 'duraznos', 'nectarina']),
  F('sandia', 'Sandía', 30, 0.6, 8, 0.2, 0.4, 'Frutas', ['sandia']),
  F('melon', 'Melón', 34, 0.8, 8, 0.2, 0.9, 'Frutas', ['melon']),
  F('papaya', 'Papaya', 43, 0.5, 11, 0.3, 1.7, 'Frutas', ['papaya']),
  F('guayaba', 'Guayaba', 68, 2.6, 14, 1, 5.4, 'Frutas', ['guayaba']),
  F('limon', 'Limón', 29, 1.1, 9, 0.3, 2.8, 'Frutas', ['jugo de limon', 'limon', 'limones', 'lima']),
  F('tamarindo', 'Tamarindo', 239, 2.8, 63, 0.6, 5, 'Frutas', ['tamarindo']),
  F('frijol', 'Frijol', 127, 8.9, 23, 0.5, 8.7, 'Leguminosas', ['frijol negro', 'frijol', 'frijoles', 'frijol refrito', 'frijoles refritos', 'haba', 'lenteja', 'lentejas', 'garbanzo']),
  F('agua', 'Agua', 0, 0, 0, 0, 0, 'Libres en energía', ['agua']),
  F('hielo', 'Hielo', 0, 0, 0, 0, 0, 'Libres en energía', ['hielo']),
  F('sal', 'Sal', 0, 0, 0, 0, 0, 'Libres en energía', ['sal de mar', 'sal rosa', 'sal']),
  F('pimienta', 'Pimienta', 0, 0, 0, 0, 0, 'Libres en energía', ['pimienta']),
  F('canela', 'Canela', 0, 0, 0, 0, 0, 'Libres en energía', ['canela']),
  F('vainilla', 'Vainilla', 0, 0, 0, 0, 0, 'Libres en energía', ['extracto de vainilla', 'vainilla', 'esencia de vainilla']),
  F('comino', 'Comino', 0, 0, 0, 0, 0, 'Libres en energía', ['comino']),
  F('oregano', 'Orégano', 0, 0, 0, 0, 0, 'Libres en energía', ['oregano', 'especias', 'paprika', 'curry', 'tomillo']),
  F('chilepolvo', 'Chile en polvo', 282, 13, 50, 14, 27, 'Verduras', ['chile en polvo', 'chile polvo', 'tajin', 'pimenton', 'pimenton ahumado']),
  F('fruta', 'Fruta mixta', 55, 0.6, 14, 0.2, 2.2, 'Frutas', ['fruta', 'frutas']),
  F('sustitutovegano', 'Sustituto de huevo vegano', 50, 2, 3, 3, 2, 'Leguminosas', ['sustituto vegano', 'sustituto de huevo', 'huevo de linaza', 'linaza molida con agua']),
]

export const DEFAULT_FOOD = F('otros', 'Otros ingredientes (aprox)', 50, 3, 5, 2, 1, 'Verduras', ['otros'])
